.PHONY: all clean

BIN = exp.out

all:
	g++ exp.cpp funciones.cpp ../../implementacion/ej3/aux.cpp ../../implementacion/ej3/Grafo.cpp ../../implementacion/ej3/Camino.cpp ../../implementacion/ej2/funciones.cpp ../../implementacion/ej1bis/backtracking.cpp ../../implementacion/ej1bis/heuristica.cpp -std=c++11 -o exp.out

clean:
	rm -f $(BIN)