.PHONY: all clean

BIN = ej1Exp.out gen.out

all:
	g++ ej.cpp ../../implementacion/ej1/backtracking.cpp ../../implementacion/ej2/heuristica.cpp -std=c++11 -o ej1Exp.out
	# g++ gen.cpp -std=c++11 -o gen.out

clean:
	rm -f $(BIN)
