.PHONY: all clean

BIN = ej2 ej2SH

	# g++ SegundaHeuristica.cpp -std=c++11 -o ej2SH # NO TIENE MAIN ACÁ
all:
	g++ ej2.cpp funciones.cpp -std=c++11 -o ej2

borrartests:
	rm -f *.txt

clean:
	rm -f $(BIN)